language: python
python:
  - "2.7"
  - "3.3"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository -y 'deb http://neuro.debian.net/debian data main'
  - sudo add-apt-repository -y 'deb http://neuro.debian.net/debian precise main'
  - sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
  - sudo apt-get update
  - sudo apt-get install -qq python-pandas python3-pandas
install:
  - pip install -r requirements.txt --use-mirrors
script: make test
